// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A representation of a blockchain node.
public struct BlockchainNode: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The fully qualified name of the blockchain node.
  /// e.g. `projects/my-project/locations/us-central1/blockchainNodes/my-node`.
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp at which the blockchain node was first created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The timestamp at which the blockchain node was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// User-provided key-value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Immutable. The blockchain type of the node.
  public var blockchainType: BlockchainNode.BlockchainType? = nil

  /// Output only. The connection information used to interact with a blockchain
  /// node.
  public var connectionInfo: BlockchainNode.ConnectionInfo? = nil

  /// Output only. A status representing the state of the node.
  public var state: BlockchainNode.State = BlockchainNode.State()

  /// Optional. When true, the node is only accessible via Private Service
  /// Connect; no public endpoints are exposed. Otherwise, the node is only
  /// accessible via public endpoints. Warning: These nodes are deprecated,
  /// please use public endpoints instead.
  @available(*, deprecated)
  public var privateServiceConnectEnabled: Swift.Bool = Swift.Bool()

  /// Information that is specific to a particular blockchain type.
  public var blockchainTypeDetails: BlockchainTypeDetailsOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BlockchainNode`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BlockchainNode().with { $0.ethereumDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ethereumDetails = CodingKeys(stringValue: "ethereumDetails")
    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let blockchainType = CodingKeys(stringValue: "blockchainType")
    static let connectionInfo = CodingKeys(stringValue: "connectionInfo")
    static let state = CodingKeys(stringValue: "state")
    static let privateServiceConnectEnabled = CodingKeys(
      stringValue: "privateServiceConnectEnabled")

    static let _knownKeys: Set<Swift.String> = [
      "ethereumDetails",
      "name",
      "createTime",
      "updateTime",
      "labels",
      "blockchainType",
      "connectionInfo",
      "state",
      "privateServiceConnectEnabled",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.blockchainType = try container.decodeIfPresent(
      BlockchainNode.BlockchainType.self, forKey: .blockchainType)
    self.connectionInfo = try container.decodeIfPresent(
      BlockchainNode.ConnectionInfo.self, forKey: .connectionInfo)
    if let value = try container.decodeIfPresent(BlockchainNode.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .privateServiceConnectEnabled)
    {
      self.privateServiceConnectEnabled = value
    }

    var blockchainTypeDetails: BlockchainTypeDetailsOneOf? = nil
    let blockchainTypeDetailsCheckAndSet = {
      if blockchainTypeDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'blockchainTypeDetails'"))
      }
      blockchainTypeDetails = $0
    }
    if let ethereumDetails = try container.decodeIfPresent(
      BlockchainNode.EthereumDetails?.self, forKey: .ethereumDetails)
    {
      try blockchainTypeDetailsCheckAndSet(.ethereumDetails(ethereumDetails))
    }
    self.blockchainTypeDetails = blockchainTypeDetails
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.blockchainType, forKey: .blockchainType)
    try container.encodeIfPresent(self.connectionInfo, forKey: .connectionInfo)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.privateServiceConnectEnabled, forKey: .privateServiceConnectEnabled)

    if let choice = self.blockchainTypeDetails {
      switch choice {
      case .ethereumDetails(let value):
        try container.encode(value, forKey: .ethereumDetails)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The connection information through which to interact with a blockchain
  /// node.
  public struct ConnectionInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The endpoint information through which to interact with a
    /// blockchain node.
    public var endpointInfo: BlockchainNode.ConnectionInfo.EndpointInfo? = nil

    /// Output only. A service attachment that exposes a node, and has the
    /// following format:
    /// projects/{project}/regions/{region}/serviceAttachments/{service_attachment_name}
    public var serviceAttachment: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConnectionInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConnectionInfo().with { $0.endpointInfo = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let endpointInfo = CodingKeys(stringValue: "endpointInfo")
      static let serviceAttachment = CodingKeys(stringValue: "serviceAttachment")

      static let _knownKeys: Set<Swift.String> = [
        "endpointInfo",
        "serviceAttachment",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.endpointInfo = try container.decodeIfPresent(
        BlockchainNode.ConnectionInfo.EndpointInfo.self, forKey: .endpointInfo)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAttachment) {
        self.serviceAttachment = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.endpointInfo, forKey: .endpointInfo)
      try container.encode(self.serviceAttachment, forKey: .serviceAttachment)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Contains endpoint information through which to interact with a blockchain
    /// node.
    public struct EndpointInfo: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Output only. The assigned URL for the node JSON-RPC API endpoint.
      public var jsonRpcApiEndpoint: Swift.String = Swift.String()

      /// Output only. The assigned URL for the node WebSockets API endpoint.
      public var websocketsApiEndpoint: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `EndpointInfo`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = EndpointInfo().with { $0.jsonRpcApiEndpoint = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let jsonRpcApiEndpoint = CodingKeys(stringValue: "jsonRpcApiEndpoint")
        static let websocketsApiEndpoint = CodingKeys(stringValue: "websocketsApiEndpoint")

        static let _knownKeys: Set<Swift.String> = [
          "jsonRpcApiEndpoint",
          "websocketsApiEndpoint",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jsonRpcApiEndpoint)
        {
          self.jsonRpcApiEndpoint = value
        }
        if let value = try container.decodeIfPresent(
          Swift.String.self, forKey: .websocketsApiEndpoint)
        {
          self.websocketsApiEndpoint = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.jsonRpcApiEndpoint, forKey: .jsonRpcApiEndpoint)
        try container.encode(self.websocketsApiEndpoint, forKey: .websocketsApiEndpoint)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.blockchainnodeengine.v1.BlockchainNode.ConnectionInfo.EndpointInfo"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.blockchainnodeengine.v1.BlockchainNode.ConnectionInfo"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Ethereum-specific blockchain node details.
  public struct EthereumDetails: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Immutable. The Ethereum environment being accessed.
    public var network: BlockchainNode.EthereumDetails.Network? = nil

    /// Immutable. The type of Ethereum node.
    public var nodeType: BlockchainNode.EthereumDetails.NodeType? = nil

    /// Immutable. The execution client
    public var executionClient: BlockchainNode.EthereumDetails.ExecutionClient? = nil

    /// Immutable. The consensus client.
    public var consensusClient: BlockchainNode.EthereumDetails.ConsensusClient? = nil

    /// Immutable. Enables JSON-RPC access to functions in the `admin` namespace.
    /// Defaults to `false`.
    public var apiEnableAdmin: Swift.Bool? = nil

    /// Immutable. Enables JSON-RPC access to functions in the `debug` namespace.
    /// Defaults to `false`.
    public var apiEnableDebug: Swift.Bool? = nil

    /// Output only. Ethereum-specific endpoint information.
    public var additionalEndpoints: BlockchainNode.EthereumDetails.EthereumEndpoints? = nil

    /// Configuration for validator-related parameters on the beacon client,
    /// and for any GCP-managed validator client.
    public var validatorConfig: BlockchainNode.EthereumDetails.ValidatorConfig? = nil

    /// Options for the execution client.
    public var executionClientDetails: ExecutionClientDetailsOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EthereumDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EthereumDetails().with { $0.gethDetails = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let gethDetails = CodingKeys(stringValue: "gethDetails")
      static let network = CodingKeys(stringValue: "network")
      static let nodeType = CodingKeys(stringValue: "nodeType")
      static let executionClient = CodingKeys(stringValue: "executionClient")
      static let consensusClient = CodingKeys(stringValue: "consensusClient")
      static let apiEnableAdmin = CodingKeys(stringValue: "apiEnableAdmin")
      static let apiEnableDebug = CodingKeys(stringValue: "apiEnableDebug")
      static let additionalEndpoints = CodingKeys(stringValue: "additionalEndpoints")
      static let validatorConfig = CodingKeys(stringValue: "validatorConfig")

      static let _knownKeys: Set<Swift.String> = [
        "gethDetails",
        "network",
        "nodeType",
        "executionClient",
        "consensusClient",
        "apiEnableAdmin",
        "apiEnableDebug",
        "additionalEndpoints",
        "validatorConfig",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.network = try container.decodeIfPresent(
        BlockchainNode.EthereumDetails.Network.self, forKey: .network)
      self.nodeType = try container.decodeIfPresent(
        BlockchainNode.EthereumDetails.NodeType.self, forKey: .nodeType)
      self.executionClient = try container.decodeIfPresent(
        BlockchainNode.EthereumDetails.ExecutionClient.self, forKey: .executionClient)
      self.consensusClient = try container.decodeIfPresent(
        BlockchainNode.EthereumDetails.ConsensusClient.self, forKey: .consensusClient)
      self.apiEnableAdmin = try container.decodeIfPresent(Swift.Bool.self, forKey: .apiEnableAdmin)
      self.apiEnableDebug = try container.decodeIfPresent(Swift.Bool.self, forKey: .apiEnableDebug)
      self.additionalEndpoints = try container.decodeIfPresent(
        BlockchainNode.EthereumDetails.EthereumEndpoints.self, forKey: .additionalEndpoints)
      self.validatorConfig = try container.decodeIfPresent(
        BlockchainNode.EthereumDetails.ValidatorConfig.self, forKey: .validatorConfig)

      var executionClientDetails: ExecutionClientDetailsOneOf? = nil
      let executionClientDetailsCheckAndSet = {
        if executionClientDetails != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'executionClientDetails'"))
        }
        executionClientDetails = $0
      }
      if let gethDetails = try container.decodeIfPresent(
        BlockchainNode.EthereumDetails.GethDetails?.self, forKey: .gethDetails)
      {
        try executionClientDetailsCheckAndSet(.gethDetails(gethDetails))
      }
      self.executionClientDetails = executionClientDetails
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.network, forKey: .network)
      try container.encodeIfPresent(self.nodeType, forKey: .nodeType)
      try container.encodeIfPresent(self.executionClient, forKey: .executionClient)
      try container.encodeIfPresent(self.consensusClient, forKey: .consensusClient)
      try container.encodeIfPresent(self.apiEnableAdmin, forKey: .apiEnableAdmin)
      try container.encodeIfPresent(self.apiEnableDebug, forKey: .apiEnableDebug)
      try container.encodeIfPresent(self.additionalEndpoints, forKey: .additionalEndpoints)
      try container.encodeIfPresent(self.validatorConfig, forKey: .validatorConfig)

      if let choice = self.executionClientDetails {
        switch choice {
        case .gethDetails(let value):
          try container.encode(value, forKey: .gethDetails)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Options for the Geth execution client.
    ///
    /// See [Command-line
    /// Options](https://geth.ethereum.org/docs/fundamentals/command-line-options)
    /// for more details.
    public struct GethDetails: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Immutable. Blockchain garbage collection mode.
      public var garbageCollectionMode:
        BlockchainNode.EthereumDetails.GethDetails.GarbageCollectionMode? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `GethDetails`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GethDetails().with { $0.garbageCollectionMode = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let garbageCollectionMode = CodingKeys(stringValue: "garbageCollectionMode")

        static let _knownKeys: Set<Swift.String> = [
          "garbageCollectionMode"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.garbageCollectionMode = try container.decodeIfPresent(
          BlockchainNode.EthereumDetails.GethDetails.GarbageCollectionMode.self,
          forKey: .garbageCollectionMode)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.garbageCollectionMode, forKey: .garbageCollectionMode)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// Blockchain garbage collection modes. Only applicable when `NodeType` is
      /// `FULL` or `ARCHIVE`.
      ///
      /// - Note: Adding cases to this enumeration is not considered a breaking change.
      ///   Always include an `@unknown default:` case when switching over this type.
      ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
      ///   expecting specific values to remain unparsed; future releases may promote
      ///   them to named cases.
      public enum GarbageCollectionMode: Codable, Equatable, Hashable, Sendable {
        /// The garbage collection has not been specified.
        case unspecified
        /// Configures Geth's garbage collection so that older data not needed
        /// for a full node is deleted. This is the default mode when creating a
        /// full node.
        case full
        /// Configures Geth's garbage collection so that old data is never
        /// deleted. This is the default mode when creating an archive node. This
        /// value can also be chosen when creating a full node in order to create
        /// a partial/recent archive node. See
        /// [Sync modes](https://geth.ethereum.org/docs/fundamentals/sync-modes)
        /// for more details.
        case archive
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific integer values in this case;
        ///   future releases may promote them to named enum cases.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific string literals in this case;
        ///   future releases may promote them to named enum cases.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .full: return 1
          case .archive: return 2
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "GARBAGE_COLLECTION_MODE_UNSPECIFIED"
          case .full: return "FULL"
          case .archive: return "ARCHIVE"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:GarbageCollectionMode/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "GARBAGE_COLLECTION_MODE_UNSPECIFIED": self = .unspecified
          case "FULL": self = .full
          case "ARCHIVE": self = .archive
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:GarbageCollectionMode/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .full
          case 2: self = .archive
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode("GARBAGE_COLLECTION_MODE_UNSPECIFIED")
          case .full: return try container.encode("FULL")
          case .archive: return try container.encode("ARCHIVE")
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.blockchainnodeengine.v1.BlockchainNode.EthereumDetails.GethDetails"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Contains endpoint information specific to Ethereum nodes.
    public struct EthereumEndpoints: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Output only. The assigned URL for the node's Beacon API endpoint.
      public var beaconApiEndpoint: Swift.String = Swift.String()

      /// Output only. The assigned URL for the node's Beacon Prometheus metrics
      /// endpoint. See [Prometheus
      /// Metrics](https://lighthouse-book.sigmaprime.io/advanced_metrics.html)
      /// for more details.
      public var beaconPrometheusMetricsApiEndpoint: Swift.String = Swift.String()

      /// Output only. The assigned URL for the node's execution client's
      /// Prometheus metrics endpoint.
      public var executionClientPrometheusMetricsApiEndpoint: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `EthereumEndpoints`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = EthereumEndpoints().with { $0.beaconApiEndpoint = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let beaconApiEndpoint = CodingKeys(stringValue: "beaconApiEndpoint")
        static let beaconPrometheusMetricsApiEndpoint = CodingKeys(
          stringValue: "beaconPrometheusMetricsApiEndpoint")
        static let executionClientPrometheusMetricsApiEndpoint = CodingKeys(
          stringValue: "executionClientPrometheusMetricsApiEndpoint")

        static let _knownKeys: Set<Swift.String> = [
          "beaconApiEndpoint",
          "beaconPrometheusMetricsApiEndpoint",
          "executionClientPrometheusMetricsApiEndpoint",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .beaconApiEndpoint)
        {
          self.beaconApiEndpoint = value
        }
        if let value = try container.decodeIfPresent(
          Swift.String.self, forKey: .beaconPrometheusMetricsApiEndpoint)
        {
          self.beaconPrometheusMetricsApiEndpoint = value
        }
        if let value = try container.decodeIfPresent(
          Swift.String.self, forKey: .executionClientPrometheusMetricsApiEndpoint)
        {
          self.executionClientPrometheusMetricsApiEndpoint = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.beaconApiEndpoint, forKey: .beaconApiEndpoint)
        try container.encode(
          self.beaconPrometheusMetricsApiEndpoint, forKey: .beaconPrometheusMetricsApiEndpoint)
        try container.encode(
          self.executionClientPrometheusMetricsApiEndpoint,
          forKey: .executionClientPrometheusMetricsApiEndpoint)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.blockchainnodeengine.v1.BlockchainNode.EthereumDetails.EthereumEndpoints"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Configuration for validator-related parameters on the beacon client,
    /// and for any GCP-managed validator client.
    public struct ValidatorConfig: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// URLs for MEV-relay services to use for block building. When set, a
      /// GCP-managed MEV-boost service is configured on the beacon client.
      public var mevRelayUrls: [Swift.String] = []

      /// Immutable. When true, deploys a GCP-managed validator client alongside
      /// the beacon client.
      @available(*, deprecated)
      public var managedValidatorClient: Swift.Bool = Swift.Bool()

      /// An Ethereum address which the beacon client will send fee rewards to if
      /// no recipient is configured in the validator client.
      ///
      /// See https://lighthouse-book.sigmaprime.io/suggested-fee-recipient.html
      /// or https://docs.prylabs.network/docs/execution-node/fee-recipient for
      /// examples of how this is used.
      ///
      /// Note that while this is often described as "suggested", as we run the
      /// execution node we can trust the execution node, and therefore this is
      /// considered enforced.
      public var beaconFeeRecipient: Swift.String? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ValidatorConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ValidatorConfig().with { $0.mevRelayUrls = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let mevRelayUrls = CodingKeys(stringValue: "mevRelayUrls")
        static let managedValidatorClient = CodingKeys(stringValue: "managedValidatorClient")
        static let beaconFeeRecipient = CodingKeys(stringValue: "beaconFeeRecipient")

        static let _knownKeys: Set<Swift.String> = [
          "mevRelayUrls",
          "managedValidatorClient",
          "beaconFeeRecipient",
        ]
      }

      #if hasAttribute(diagnose)
        @diagnose(DeprecatedDeclaration, as: ignored)
      #endif
      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .mevRelayUrls) {
          self.mevRelayUrls = value
        }
        if let value = try container.decodeIfPresent(
          Swift.Bool.self, forKey: .managedValidatorClient)
        {
          self.managedValidatorClient = value
        }
        self.beaconFeeRecipient = try container.decodeIfPresent(
          Swift.String.self, forKey: .beaconFeeRecipient)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      #if hasAttribute(diagnose)
        @diagnose(DeprecatedDeclaration, as: ignored)
      #endif
      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.mevRelayUrls, forKey: .mevRelayUrls)
        try container.encode(self.managedValidatorClient, forKey: .managedValidatorClient)
        try container.encodeIfPresent(self.beaconFeeRecipient, forKey: .beaconFeeRecipient)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.blockchainnodeengine.v1.BlockchainNode.EthereumDetails.ValidatorConfig"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The Ethereum environment being accessed.
    ///
    /// See [Networks](https://ethereum.org/en/developers/docs/networks)
    /// for more details.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum Network: Codable, Equatable, Hashable, Sendable {
      /// The network has not been specified, but should be.
      case unspecified
      /// The Ethereum Mainnet.
      case mainnet
      /// Deprecated: The Ethereum Testnet based on Goerli protocol. Please
      /// use another test network.
      @available(*, deprecated)
      case testnetGoerliPrater
      /// The Ethereum Testnet based on Sepolia/Bepolia protocol.
      /// See https://github.com/eth-clients/sepolia.
      case testnetSepolia
      /// The Ethereum Testnet based on Holesky specification.
      /// See https://github.com/eth-clients/holesky.
      case testnetHolesky
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .mainnet: return 1
        case .testnetGoerliPrater: return 2
        case .testnetSepolia: return 3
        case .testnetHolesky: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "NETWORK_UNSPECIFIED"
        case .mainnet: return "MAINNET"
        case .testnetGoerliPrater: return "TESTNET_GOERLI_PRATER"
        case .testnetSepolia: return "TESTNET_SEPOLIA"
        case .testnetHolesky: return "TESTNET_HOLESKY"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Network/unknownStringValue(_:)).
      #if hasAttribute(diagnose)
        @diagnose(DeprecatedDeclaration, as: ignored)
      #endif
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "NETWORK_UNSPECIFIED": self = .unspecified
        case "MAINNET": self = .mainnet
        case "TESTNET_GOERLI_PRATER": self = .testnetGoerliPrater
        case "TESTNET_SEPOLIA": self = .testnetSepolia
        case "TESTNET_HOLESKY": self = .testnetHolesky
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Network/unknownIntValue(_:)).
      #if hasAttribute(diagnose)
        @diagnose(DeprecatedDeclaration, as: ignored)
      #endif
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .mainnet
        case 2: self = .testnetGoerliPrater
        case 3: self = .testnetSepolia
        case 4: self = .testnetHolesky
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("NETWORK_UNSPECIFIED")
        case .mainnet: return try container.encode("MAINNET")
        case .testnetGoerliPrater: return try container.encode("TESTNET_GOERLI_PRATER")
        case .testnetSepolia: return try container.encode("TESTNET_SEPOLIA")
        case .testnetHolesky: return try container.encode("TESTNET_HOLESKY")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type of Ethereum node.
    ///
    /// See
    /// [Node
    /// Types](https://ethereum.org/en/developers/docs/nodes-and-clients/#node-types)
    /// for more details.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum NodeType: Codable, Equatable, Hashable, Sendable {
      /// Node type has not been specified, but should be.
      case unspecified
      /// An Ethereum node that only downloads Ethereum block headers.
      case light
      /// Keeps a complete copy of the blockchain data, and contributes to the
      /// network by receiving, validating, and forwarding transactions.
      case full
      /// Holds the same data as full node as well as all of the blockchain's
      /// history state data dating back to the Genesis Block.
      case archive
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .light: return 1
        case .full: return 2
        case .archive: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "NODE_TYPE_UNSPECIFIED"
        case .light: return "LIGHT"
        case .full: return "FULL"
        case .archive: return "ARCHIVE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NodeType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "NODE_TYPE_UNSPECIFIED": self = .unspecified
        case "LIGHT": self = .light
        case "FULL": self = .full
        case "ARCHIVE": self = .archive
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NodeType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .light
        case 2: self = .full
        case 3: self = .archive
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("NODE_TYPE_UNSPECIFIED")
        case .light: return try container.encode("LIGHT")
        case .full: return try container.encode("FULL")
        case .archive: return try container.encode("ARCHIVE")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The execution client (i.e., Execution Engine or EL client) listens to new
    /// transactions broadcast in the network, executes them in EVM, and holds
    /// the latest state and database of all current Ethereum data.
    ///
    /// See
    /// [What are nodes and
    /// clients?](https://ethereum.org/en/developers/docs/nodes-and-clients/#what-are-nodes-and-clients)
    /// for more details.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ExecutionClient: Codable, Equatable, Hashable, Sendable {
      /// Execution client has not been specified, but should be.
      case unspecified
      /// Official Go implementation of the Ethereum protocol.
      /// See [go-ethereum](https://geth.ethereum.org/) for details.
      case geth
      /// An implementation of Ethereum (execution client), on the efficiency
      /// frontier, written in Go. See [Erigon on
      /// GitHub](https://github.com/ledgerwatch/erigon) for details.
      case erigon
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .geth: return 1
        case .erigon: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "EXECUTION_CLIENT_UNSPECIFIED"
        case .geth: return "GETH"
        case .erigon: return "ERIGON"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ExecutionClient/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "EXECUTION_CLIENT_UNSPECIFIED": self = .unspecified
        case "GETH": self = .geth
        case "ERIGON": self = .erigon
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ExecutionClient/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .geth
        case 2: self = .erigon
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("EXECUTION_CLIENT_UNSPECIFIED")
        case .geth: return try container.encode("GETH")
        case .erigon: return try container.encode("ERIGON")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The consensus client (also referred to as beacon node or CL client)
    /// implements the proof-of-stake consensus algorithm, which enables the
    /// network to achieve agreement based on validated data from the
    /// execution client.
    ///
    /// See
    /// [What are nodes and
    /// clients?](https://ethereum.org/en/developers/docs/nodes-and-clients/#what-are-nodes-and-clients)
    /// for more details.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ConsensusClient: Codable, Equatable, Hashable, Sendable {
      /// Consensus client has not been specified, but should be.
      case unspecified
      /// Consensus client implementation written in Rust, maintained by Sigma
      /// Prime. See [Lighthouse - Sigma
      /// Prime](https://lighthouse.sigmaprime.io/) for details.
      case lighthouse
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .lighthouse: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CONSENSUS_CLIENT_UNSPECIFIED"
        case .lighthouse: return "LIGHTHOUSE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConsensusClient/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CONSENSUS_CLIENT_UNSPECIFIED": self = .unspecified
        case "LIGHTHOUSE": self = .lighthouse
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConsensusClient/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .lighthouse
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("CONSENSUS_CLIENT_UNSPECIFIED")
        case .lighthouse: return try container.encode("LIGHTHOUSE")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Options for the execution client.
    public enum ExecutionClientDetailsOneOf: Codable, Equatable, Sendable {
      /// Details for the Geth execution client.
      indirect case gethDetails(BlockchainNode.EthereumDetails.GethDetails?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.blockchainnodeengine.v1.BlockchainNode.EthereumDetails"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The blockchain type of the node.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum BlockchainType: Codable, Equatable, Hashable, Sendable {
    /// Blockchain type has not been specified, but should be.
    case unspecified
    /// The blockchain type is Ethereum.
    case ethereum
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ethereum: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BLOCKCHAIN_TYPE_UNSPECIFIED"
      case .ethereum: return "ETHEREUM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BlockchainType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BLOCKCHAIN_TYPE_UNSPECIFIED": self = .unspecified
      case "ETHEREUM": self = .ethereum
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BlockchainType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ethereum
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("BLOCKCHAIN_TYPE_UNSPECIFIED")
      case .ethereum: return try container.encode("ETHEREUM")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// All possible states for a given blockchain node.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// The state has not been specified.
    case unspecified
    /// The node has been requested and is in the process of being created.
    case creating
    /// The existing node is undergoing deletion, but is not yet finished.
    case deleting
    /// The node is running and ready for use.
    case running
    /// The node is in an unexpected or errored state.
    case error
    /// The node is currently being updated.
    case updating
    /// The node is currently being repaired.
    case repairing
    /// The node is currently being reconciled.
    case reconciling
    /// The node is syncing, which is the process by which it obtains the latest
    /// block and current global state.
    case syncing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .deleting: return 2
      case .running: return 4
      case .error: return 5
      case .updating: return 6
      case .repairing: return 7
      case .reconciling: return 8
      case .syncing: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .running: return "RUNNING"
      case .error: return "ERROR"
      case .updating: return "UPDATING"
      case .repairing: return "REPAIRING"
      case .reconciling: return "RECONCILING"
      case .syncing: return "SYNCING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "RUNNING": self = .running
      case "ERROR": self = .error
      case "UPDATING": self = .updating
      case "REPAIRING": self = .repairing
      case "RECONCILING": self = .reconciling
      case "SYNCING": self = .syncing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .deleting
      case 4: self = .running
      case 5: self = .error
      case 6: self = .updating
      case 7: self = .repairing
      case 8: self = .reconciling
      case 9: self = .syncing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .deleting: return try container.encode("DELETING")
      case .running: return try container.encode("RUNNING")
      case .error: return try container.encode("ERROR")
      case .updating: return try container.encode("UPDATING")
      case .repairing: return try container.encode("REPAIRING")
      case .reconciling: return try container.encode("RECONCILING")
      case .syncing: return try container.encode("SYNCING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Information that is specific to a particular blockchain type.
  public enum BlockchainTypeDetailsOneOf: Codable, Equatable, Sendable {
    /// Ethereum-specific blockchain node details.
    indirect case ethereumDetails(BlockchainNode.EthereumDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.blockchainnodeengine.v1.BlockchainNode"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
