// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// This service is the control plane API for Blockchain Node Engine,
/// and can be used to create, read, and delete blockchain nodes.
///
/// @Snippet(path: "BlockchainNodeEngineQuickstart")
public final class BlockchainNodeEngineClient: Clients.BlockchainNodeEngineProtocol, Sendable {
  let inner: any Clients.BlockchainNodeEngineStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `BlockchainNodeEngineClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.BlockchainNodeEngineStub = try Clients.BlockchainNodeEngineTransport(
      options)
    inner = Clients.BlockchainNodeEngineRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.BlockchainNodeEngineLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists blockchain nodes in a given project and location.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_ListBlockchainNodes")
  public func listBlockchainNodes(
    request: ListBlockchainNodesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBlockChainNodeEngineV1.ListBlockchainNodesResponse {
    try await self.inner.listBlockchainNodes(request: request, options: options)
  }

  /// Lists blockchain nodes in a given project and location.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_ListBlockchainNodes")
  public func listBlockchainNodes(
    byItem: ListBlockchainNodesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<BlockchainNode, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudBlockChainNodeEngineV1.ListBlockchainNodesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listBlockchainNodes(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single blockchain node.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_GetBlockchainNode")
  public func getBlockchainNode(
    request: GetBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBlockChainNodeEngineV1.BlockchainNode {
    try await self.inner.getBlockchainNode(request: request, options: options)
  }

  /// Creates a new blockchain node in a given project and location.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_CreateBlockchainNode")
  public func createBlockchainNode(
    request: CreateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createBlockchainNode(request: request, options: options)
  }

  /// Creates a new blockchain node in a given project and location.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_CreateBlockchainNode")
  public func createBlockchainNode(
    withPolling: CreateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BlockchainNode> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<BlockchainNode>.State in
      return try op._extractStatus(BlockchainNode.self)
    }
    let rawOp = try await self.createBlockchainNode(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<BlockchainNode>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single blockchain node.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_UpdateBlockchainNode")
  public func updateBlockchainNode(
    request: UpdateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateBlockchainNode(request: request, options: options)
  }

  /// Updates the parameters of a single blockchain node.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_UpdateBlockchainNode")
  public func updateBlockchainNode(
    withPolling: UpdateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BlockchainNode> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<BlockchainNode>.State in
      return try op._extractStatus(BlockchainNode.self)
    }
    let rawOp = try await self.updateBlockchainNode(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<BlockchainNode>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single blockchain node.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_DeleteBlockchainNode")
  public func deleteBlockchainNode(
    request: DeleteBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteBlockchainNode(request: request, options: options)
  }

  /// Deletes a single blockchain node.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_DeleteBlockchainNode")
  public func deleteBlockchainNode(
    withPolling: DeleteBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteBlockchainNode(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "BlockchainNodeEngine_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BlockchainNodeEngine_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BlockchainNodeEngine_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BlockchainNodeEngine_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BlockchainNodeEngine_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "BlockchainNodeEngine_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `BlockchainNodeEngineClient`.
  ///
  /// To mock `BlockchainNodeEngineClient` change your functions to receive
  /// `some BlockchainNodeEngineProtocol` or `any BlockchainNodeEngineProtocol`
  /// and pass a mock implementation in your tests.
  public protocol BlockchainNodeEngineProtocol {
    /// See `BlockchainNodeEngineClient.listBlockchainNodes`.
    func listBlockchainNodes(request: ListBlockchainNodesRequest) async throws
      -> GoogleCloudBlockChainNodeEngineV1.ListBlockchainNodesResponse

    /// See `BlockchainNodeEngineClient.listBlockchainNodes`.
    func listBlockchainNodes(
      byItem: ListBlockchainNodesRequest
    ) throws -> any AsyncSequence<BlockchainNode, Swift.Error>

    /// See `BlockchainNodeEngineClient.listBlockchainNodes`.
    func listBlockchainNodes(
      parent: Swift.String,
    ) throws -> any AsyncSequence<BlockchainNode, Swift.Error>

    /// See `BlockchainNodeEngineClient.getBlockchainNode`.
    func getBlockchainNode(request: GetBlockchainNodeRequest) async throws
      -> GoogleCloudBlockChainNodeEngineV1.BlockchainNode

    /// See `BlockchainNodeEngineClient.getBlockchainNode`.
    func getBlockchainNode(
      name: Swift.String,
    ) async throws -> GoogleCloudBlockChainNodeEngineV1.BlockchainNode

    /// See `BlockchainNodeEngineClient.createBlockchainNode`.
    func createBlockchainNode(request: CreateBlockchainNodeRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `BlockchainNodeEngineClient.createBlockchainNode`.
    func createBlockchainNode(withPolling: CreateBlockchainNodeRequest) async throws
      -> any GoogleCloudGax.PollableOperation<BlockchainNode>

    /// See `BlockchainNodeEngineClient.createBlockchainNode`.
    func createBlockchainNode(
      parent: Swift.String,
      blockchainNode: BlockchainNode?,
      blockchainNodeId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<BlockchainNode>

    /// See `BlockchainNodeEngineClient.updateBlockchainNode`.
    func updateBlockchainNode(request: UpdateBlockchainNodeRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `BlockchainNodeEngineClient.updateBlockchainNode`.
    func updateBlockchainNode(withPolling: UpdateBlockchainNodeRequest) async throws
      -> any GoogleCloudGax.PollableOperation<BlockchainNode>

    /// See `BlockchainNodeEngineClient.updateBlockchainNode`.
    func updateBlockchainNode(
      blockchainNode: BlockchainNode?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<BlockchainNode>

    /// See `BlockchainNodeEngineClient.deleteBlockchainNode`.
    func deleteBlockchainNode(request: DeleteBlockchainNodeRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `BlockchainNodeEngineClient.deleteBlockchainNode`.
    func deleteBlockchainNode(withPolling: DeleteBlockchainNodeRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `BlockchainNodeEngineClient.deleteBlockchainNode`.
    func deleteBlockchainNode(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `BlockchainNodeEngineClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `BlockchainNodeEngineClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `BlockchainNodeEngineClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `BlockchainNodeEngineClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `BlockchainNodeEngineClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `BlockchainNodeEngineClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `BlockchainNodeEngineClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `BlockchainNodeEngineClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `BlockchainNodeEngineClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `BlockchainNodeEngineClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `BlockchainNodeEngineClient.listBlockchainNodes`.
    func listBlockchainNodes(
      request: ListBlockchainNodesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBlockChainNodeEngineV1.ListBlockchainNodesResponse

    /// See `BlockchainNodeEngineClient.listBlockchainNodes`.
    func listBlockchainNodes(
      byItem: ListBlockchainNodesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<BlockchainNode, Swift.Error>

    /// See `BlockchainNodeEngineClient.getBlockchainNode`.
    func getBlockchainNode(
      request: GetBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBlockChainNodeEngineV1.BlockchainNode

    /// See `BlockchainNodeEngineClient.createBlockchainNode`.
    func createBlockchainNode(
      request: CreateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BlockchainNodeEngineClient.createBlockchainNode`.
    func createBlockchainNode(
      withPolling: CreateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<BlockchainNode>

    /// See `BlockchainNodeEngineClient.updateBlockchainNode`.
    func updateBlockchainNode(
      request: UpdateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BlockchainNodeEngineClient.updateBlockchainNode`.
    func updateBlockchainNode(
      withPolling: UpdateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<BlockchainNode>

    /// See `BlockchainNodeEngineClient.deleteBlockchainNode`.
    func deleteBlockchainNode(
      request: DeleteBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `BlockchainNodeEngineClient.deleteBlockchainNode`.
    func deleteBlockchainNode(
      withPolling: DeleteBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `BlockchainNodeEngineClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `BlockchainNodeEngineClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `BlockchainNodeEngineClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `BlockchainNodeEngineClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `BlockchainNodeEngineClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `BlockchainNodeEngineClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `BlockchainNodeEngineClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.BlockchainNodeEngineProtocol {
  public func listBlockchainNodes(request: ListBlockchainNodesRequest) async throws
    -> GoogleCloudBlockChainNodeEngineV1.ListBlockchainNodesResponse
  {
    try await self.listBlockchainNodes(request: request, options: .init())
  }

  public func listBlockchainNodes(
    request: ListBlockchainNodesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBlockChainNodeEngineV1.ListBlockchainNodesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listBlockchainNodes(
    byItem: ListBlockchainNodesRequest
  ) throws -> any AsyncSequence<BlockchainNode, Swift.Error> {
    try self.listBlockchainNodes(byItem: byItem, options: .init())
  }

  public func listBlockchainNodes(
    byItem: ListBlockchainNodesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<BlockchainNode, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudBlockChainNodeEngineV1.ListBlockchainNodesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBlockchainNodes(
    parent: Swift.String,
  ) throws -> any AsyncSequence<BlockchainNode, Swift.Error> {
    let request = ListBlockchainNodesRequest().with {
      $0.parent = parent
    }
    return try self.listBlockchainNodes(byItem: request)
  }

  public func getBlockchainNode(request: GetBlockchainNodeRequest) async throws
    -> GoogleCloudBlockChainNodeEngineV1.BlockchainNode
  {
    try await self.getBlockchainNode(request: request, options: .init())
  }

  public func getBlockchainNode(
    request: GetBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBlockChainNodeEngineV1.BlockchainNode {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getBlockchainNode(
    name: Swift.String,
  ) async throws -> GoogleCloudBlockChainNodeEngineV1.BlockchainNode {
    let request = GetBlockchainNodeRequest().with {
      $0.name = name
    }
    return try await self.getBlockchainNode(request: request)
  }

  public func createBlockchainNode(request: CreateBlockchainNodeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createBlockchainNode(request: request, options: .init())
  }

  public func createBlockchainNode(
    request: CreateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createBlockchainNode(withPolling: CreateBlockchainNodeRequest) async throws
    -> any GoogleCloudGax.PollableOperation<BlockchainNode>
  {
    try await self.createBlockchainNode(withPolling: withPolling, options: .init())
  }

  public func createBlockchainNode(
    withPolling: CreateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BlockchainNode> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<BlockchainNode>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createBlockchainNode(
    parent: Swift.String,
    blockchainNode: BlockchainNode?,
    blockchainNodeId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<BlockchainNode> {
    let request = CreateBlockchainNodeRequest().with {
      $0.parent = parent
      $0.blockchainNode = blockchainNode
      $0.blockchainNodeId = blockchainNodeId
    }
    return try await self.createBlockchainNode(withPolling: request)
  }

  public func updateBlockchainNode(request: UpdateBlockchainNodeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateBlockchainNode(request: request, options: .init())
  }

  public func updateBlockchainNode(
    request: UpdateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateBlockchainNode(withPolling: UpdateBlockchainNodeRequest) async throws
    -> any GoogleCloudGax.PollableOperation<BlockchainNode>
  {
    try await self.updateBlockchainNode(withPolling: withPolling, options: .init())
  }

  public func updateBlockchainNode(
    withPolling: UpdateBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BlockchainNode> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<BlockchainNode>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateBlockchainNode(
    blockchainNode: BlockchainNode?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<BlockchainNode> {
    let request = UpdateBlockchainNodeRequest().with {
      $0.blockchainNode = blockchainNode
      $0.updateMask = updateMask
    }
    return try await self.updateBlockchainNode(withPolling: request)
  }

  public func deleteBlockchainNode(request: DeleteBlockchainNodeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteBlockchainNode(request: request, options: .init())
  }

  public func deleteBlockchainNode(
    request: DeleteBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteBlockchainNode(withPolling: DeleteBlockchainNodeRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteBlockchainNode(withPolling: withPolling, options: .init())
  }

  public func deleteBlockchainNode(
    withPolling: DeleteBlockchainNodeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteBlockchainNode(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteBlockchainNodeRequest().with {
      $0.name = name
    }
    return try await self.deleteBlockchainNode(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
